namespace Elmer.Net.Areas.reCAPTCHA.Core
{
    public interface IReCaptchaApiRequest
    {
        /// <summary>
        /// User response token generated by reCAPTCHA client-side
        /// </summary>
        string Response { get; set; }
        /// <summary>
        /// Shared secret key for your reCAPTCHA api instance
        /// </summary>
        string Secret { get; set; }
        /// <summary>
        /// User's IP Address
        /// </summary>
        /// <remarks>Optional field</remarks>
        string? RemoteIp { get; set; }

        string ToString();
    }
}
